name: review_prompt
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  in_app_review: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1

flutter:


import_sorter:
  emojis: false
  comments: false
